fx TS error on mongodb call
```
app/models/user.js:768:15 - error TS2353: Object literal may only specify known properties, and 'multi' does not exist in type 'UpdateOptions'.

768             { multi: true },
                  ~~~~~
```