ci: Reduce risk of timeout from Cypress code-coverage plugin (#525)
## What does this PR do / solve?

Goal: reduce risk of flakiness of Cypress/e2e tests caused by timeouts from code-coverage plugin:

```
       "after all" hook: collectBackendCoverage for "user unsubscribes from email notification":
     CypressError: `cy.request()` timed out waiting `5000ms` for a response from your server.
```

cf https://github.com/openwhyd/openwhyd/runs/4638088166?check_suite_focus=true#step:8:1094

## Overview of changes

Upgrade `@cypress/code-coverage` and `istanbul-lib-coverage`, as suggested in https://github.com/cypress-io/code-coverage/issues/216#issuecomment-974791778.