fix(tests): Cypress errors (#501)
* try to fix `Unable to locate executable file`

* try to load env file using a github action

* try to fix `/entrypoint.sh: export: line 1: -o: bad variable name`
cf https://github.com/openwhyd/openwhyd/runs/4482525337?check_suite_focus=true#step:7:5

* try to upgrade cypress

* try to fix `CypressError: Timed out after waiting `60000ms` for your remote page to load.`
cf https://github.com/openwhyd/openwhyd/runs/4482557359?check_suite_focus=true#step:8:214
by using chrome browser
as suggested in https://github.com/cypress-io/cypress/issues/2118#issuecomment-580095512

* try to fix local error `The play() request was interrupted by a call to pause()`
by increasing wait time

* try to fix `Cannot read properties of null (reading 'style')`

* troubleshooting: try to display front-end logs, at least on CI

* add note

* log debug info only in case of error

* revert to cypress 8.6

* fix codacy issue

* troubleshoot playem errors

* try to fix `Cypress command timeout of `4000ms` exceeded` by disabling @cypress/code-coverage

cf https://github.com/openwhyd/openwhyd/runs/4484506970?check_suite_focus=true#step:8:5351

details:
"after each" hook for "should allow user to re-add a track into a playlist":
     CypressError: Cypress command timeout of `4000ms` exceeded.

Because this error occurred during a `after each` hook we are skipping all of the remaining tests.
      at cypressErr (http://localhost:8080/__cypress/runner/cypress_runner.js:172722:18)
      at Object.errByPath (http://localhost:8080/__cypress/runner/cypress_runner.js:172791:10)
      at http://localhost:8080/__cypress/runner/cypress_runner.js:174541:80

* fix 404 on btn-player-video.png
cf https://github.com/openwhyd/openwhyd/runs/4484636963?check_suite_focus=true#step:8:381

* fix 404 on fonts

* fix 404 on spinnerbackloadmore.png

* try to fix `Synchronous XMLHttpRequest on the main thread is deprecated`
cf https://github.com/openwhyd/openwhyd/runs/4484636963?check_suite_focus=true#step:8:443

* Revert "fix 404 on fonts"

This reverts commit 622825e93cf6dcc92bb5ca4525ff81947aaf79b4.

* prevent `cp: cannot stat 'coverage-cypress/.nyc_output/*.json': No such file or directory`
cf https://github.com/openwhyd/openwhyd/runs/4484957961?check_suite_focus=true#step:5:9

* try to fix `The play() request was interrupted by a call to pause().` by encapsulting playem's pause() into a try-catch block

* upgrade playemjs 1.2.1

* fix minified playem

* fix 404 on fonts/AvenirNext-DemiBold.otf

* visual tests still failing with timeout => trying to upgrade applitools/eyes-cypress

* try switching back to electron, even on CI

* with 'electron', visual tests are passing but acceptance e2e tests are timing out! => try 'chromium'