fix(tech-debt): replace legacy `usernames` in-memory cache by DB queries (#814)
* fix: remove usernames in-memory cache, by augment AI agent

prompt: "I want to remove the `usernames` export from that file, and replace references to it by database calls to the `user` mongodb collection, via the `fetchAndProcessUserById` function. Can you propose a plan to do that?"

* fix: also replace remaining references to `mongodb.usernames`, by augment AI agent

prompt: "can you do the same for references to `mongodb.usernames` please?"

* manually fix error revealed by `make lint`: `app/controllers/api/user.js:326:9 - error TS2339: Property 'id' does not exist on type '{}'.`

* manually fix errors revealed by `make lint`: `'mongodb' is assigned a value but never used`

* login is broken => prompt: "now, `await` all calls to `request.getUser()`, which lead to `http.IncomingMessage.prototype.getUser` defined in `logging.js`, so that logged in user session can be recognized on all routes."

* some tests are broken => prompt: "also `await` calls to `request.checkLogin()`, which lead to `http.IncomingMessage.prototype.checkLogin` defined in `logging.js`, so that logged in user session can be recognized on all routes."

* debug(integration-tests): log invalid objectId

* fix(fetchAndProcessUserById): don't throw if id is invalid

* docs(renderUserImg): clarify that param is not necessarily a userId

* Revert "debug(integration-tests): log invalid objectId"

This reverts commit 58814c7f676d5d065819de34baa168ca8a5a9b73.

* some tests are broken => prompt: "also `await` calls to `getUserFromId()` defined in `mongodb.js`, and to it's proxy: `request.getUserFromId` defined in `logging.js`"

* todo: remove old proxy functions

* fix: manually add missing await on new async calls

* some tests are broken => prompt: "also `await` calls to `getUserNameFromId()` defined in `mongodb.js`, and to it's proxy: `request.getUserNameFromId` defined in `logging.js`"

* fix: manually await calls to logged in user in admin functions + add jsdoc

* fix: manually add await that are still missing on checkLogin calls

* fix: manually add await that are still missing on getUser calls

* some tests are broken => prompt: "also `await` calls to `checkAdmin()`, defined in `logging.js`"

* fix: don't fetch all users to render the /all page

* fix(invites): add missing await in renderUserList => create fetchUserNameById() function

* fix(users): add missing await in renderItem

* optim(post): don't fetch user names twice per array item

* fix(playlistOrder): add missing await in controller

* fix/cleanup: inline `getUserFromId` function calls

* fix/cleanup: inline `getUserNameFromId` function calls

* fix: make `fetchAndProcessUserById` fetch and return just the fields that were cached in `usernames`

* fix consequential type errors

* fix: await calls to `renderTypedImg`
suggested by copilot, cf https://github.com/openwhyd/openwhyd/pull/814/files#r2080047911

* fix(playlist): made integration tests pass by being real abouy the fact that playlist ids are either numbers of strings

cf results of the query I just ran in our production db:

```
> db.user.aggregate([
...   { $unwind: "$pl" },
...   {
...     $project: {
...       typeOfPlId: { $type: "$pl.id" }
...     }
...   },
...   {
...     $group: {
...       _id: "$typeOfPlId",
...       count: { $sum: 1 }
...     }
...   },
...   {
...     $sort: { count: -1 }
...   }
... ])

{ "_id" : "int", "count" : 96956 }
{ "_id" : "string", "count" : 1765 }
{ "_id" : "double", "count" : 180 }
```

* fix(uploadedFile): make `gets user profile data` test pass

* prompt: Can you make sure that all imports to `models/user.js` (using `require`) are done at the top of each file, instead of inline?

* prompt: you missed some. e.g. in `app/models/notif.js`, but please leave `app/models/mongodb.js` as-is.

* Apply suggestions from code review

Co-authored-by: greptile-apps[bot] <165735046+greptile-apps[bot]@users.noreply.github.com>

* optim(rendering): fetch all user names at once => introduce `fetchUserNamesByIds`

...as suggested by greptile, cf https://github.com/openwhyd/openwhyd/pull/814/files#r2080051308

* fix: remove script to check the number of references to `usernames`, for progressive decommissioning

* fix(notif-api): remove last reference to `usernames`

* refactor(invites-admin): reduce complexity
cf https://sonarcloud.io/project/issues?impactSeverities=HIGH&sinceLeakPeriod=true&issueStatuses=OPEN%2CCONFIRMED&pullRequest=814&id=openwhyd_openwhyd&open=AZawXhJB8hwFZyoxNVxl

* refactor(invites-admin): reduce complexity (2)
cf https://sonarcloud.io/project/issues?impactSeverities=HIGH&sinceLeakPeriod=true&issueStatuses=OPEN%2CCONFIRMED&pullRequest=814&id=openwhyd_openwhyd&open=AZawXhJB8hwFZyoxNVxl

* refactor(invites-admin): reduce complexity (3)
cf https://sonarcloud.io/project/issues?impactSeverities=HIGH&sinceLeakPeriod=true&issueStatuses=OPEN%2CCONFIRMED&pullRequest=814&id=openwhyd_openwhyd&open=AZawXhJB8hwFZyoxNVxl

* refactor(invites-admin): reduce complexity (4)
cf https://sonarcloud.io/project/issues?impactSeverities=HIGH&sinceLeakPeriod=true&issueStatuses=OPEN%2CCONFIRMED&pullRequest=814&id=openwhyd_openwhyd&open=AZawXhJB8hwFZyoxNVxl

* fix(invites-admin): `This function expects 2 arguments, but 4 were provided`
cf https://sonarcloud.io/project/issues?impactSeverities=HIGH&sinceLeakPeriod=true&issueStatuses=OPEN%2CCONFIRMED&pullRequest=814&id=openwhyd_openwhyd&open=AZawdtjcAUehheQyccNH

* fix(uploadedFile): `Unexpected `await` of a non-Promise (non-"Thenable") value`
cf https://sonarcloud.io/project/issues?impactSeverities=HIGH&sinceLeakPeriod=true&issueStatuses=OPEN%2CCONFIRMED&pullRequest=814&id=openwhyd_openwhyd&open=AZbyVBVvaOfcVjkbQc29

* 🧹 remove TODO: fix the /all page without having to fetch all users
cf https://sonarcloud.io/project/issues?cleanCodeAttributeCategories=INTENTIONAL&impactSeverities=INFO&sinceLeakPeriod=true&issueStatuses=OPEN%2CCONFIRMED&pullRequest=814&id=openwhyd_openwhyd&open=AZawdtnlAUehheQyccNI

* fix(notif): notify mentioned user instead of user who posted the track

* 🧹 removed TODO

* fix(uploadedFile): await function calls that read from file system

* fix(invites-admin): fetch calls were not resolving
cf https://sonarcloud.io/project/issues?sinceLeakPeriod=true&issueStatuses=OPEN%2CCONFIRMED&pullRequest=814&id=openwhyd_openwhyd&open=AZbyuOcJ4P6j_mAIxz_i

* fix: remove commented code

* fix: Default parameters should be last
cf https://sonarcloud.io/project/issues?sinceLeakPeriod=true&issueStatuses=OPEN%2CCONFIRMED&pullRequest=814&id=openwhyd_openwhyd&open=AZawUCLBIsTOljq3Zk8U

* Revert "fix(uploadedFile): await function calls that read from file system"

This reverts commit deaffae7162360f0f05d1efe99891f56e98d1816.

* fix(notif-model): prefer optional chain expression
cf https://sonarcloud.io/project/issues?sinceLeakPeriod=true&issueStatuses=OPEN%2CCONFIRMED&pullRequest=814&id=openwhyd_openwhyd&open=AZarr4QA8TkDyk0DI8P6

* fix(notif-model): Default parameters should be last
cf https://sonarcloud.io/project/issues?sinceLeakPeriod=true&issueStatuses=OPEN%2CCONFIRMED&pullRequest=814&id=openwhyd_openwhyd&open=AZarr4QB8TkDyk0DI8P7

* ci: give more time for images to load, when checking for visual regressions

* ci: use `lazyLoad` option to give time to all resources to load before applitools eyes takes a screenshot

---------

Co-authored-by: greptile-apps[bot] <165735046+greptile-apps[bot]@users.noreply.github.com>