fix(api): make rate limiter work with HTTP proxy (cloudflare and/or nginx)
```
ValidationError: The 'X-Forwarded-For' header is set but the Express 'trust proxy' setting is false (default). This could indicate a misconfiguration which would prevent express-rate-limit from accurately identifying users. See https://express-rate-limit.github.io/ERR_ERL_UNEXPECTED_X_FORWARDED_FOR/ for more information.
```

cf https://github.com/openwhyd/openwhyd/pull/808#issuecomment-2754369261