fix(deps): update auth deps + some devDeps (#792)
* fix(deps): update auth deps

* migrate auth0 calls
cf https://github.com/auth0/node-auth0/blob/master/v4_MIGRATION_GUIDE.md

* downgrade approvals, as it causes typescript errors on imports

* fx TS error on mongodb call

```
app/models/user.js:768:15 - error TS2353: Object literal may only specify known properties, and 'multi' does not exist in type 'UpdateOptions'.

768             { multi: true },
                  ~~~~~
```

* `make lint` => reformat