try to fix `Cypress command timeout of `4000ms` exceeded` by disabling @cypress/code-coverage
cf https://github.com/openwhyd/openwhyd/runs/4484506970?check_suite_focus=true#step:8:5351

details:
"after each" hook for "should allow user to re-add a track into a playlist":
     CypressError: Cypress command timeout of `4000ms` exceeded.

Because this error occurred during a `after each` hook we are skipping all of the remaining tests.
      at cypressErr (http://localhost:8080/__cypress/runner/cypress_runner.js:172722:18)
      at Object.errByPath (http://localhost:8080/__cypress/runner/cypress_runner.js:172791:10)
      at http://localhost:8080/__cypress/runner/cypress_runner.js:174541:80