fix(chrome-extension): migrate to manifest version 3 (#774)
* fix(chrome-extension): migrate to manifest version 3
cf https://developer.chrome.com/docs/extensions/develop/migrate?hl=fr

* fix: can't load playem from openwhyd.org => include it in the package

* fix `ReferenceError: Cannot access 'openwhydYouTubeExtractor' before initialization`

* fix: "you can't use the official YouTube iframe api" => stop using playem from bookmarklet
cf https://groups.google.com/a/chromium.org/g/chromium-extensions/c/29qQJmIUdZw?pli=1

* docs: browser extension

* docs: clarify that documentation files are accessible from https://openwhyd.github.io/openwhyd

* fix(lint): `Property 'BandcampPlayer' does not exist on type 'Window & typeof globalThis'.` in public/js/whydPlayer.js

* format files (make lint)

* fix(vscode): also use prettier to format json files

* disable tests on Bandcamp and SoundCloud track detection
cf https://github.com/openwhyd/openwhyd/actions/runs/10439695373/job/28908671111?pr=774#step:10:511